### ISSUE TITLE
Write a doc about Tailwindcss

### ISSUE THREAD

**Issue by sithumonline** [sliit-foss/zero2hero#21]
**_Please assign yourself before you start work on it._**

**Comment by KanishkKhurana** [comment]
hey! i'd like to contribute to this , but i have a question. do we have to create a react page for the doc we are writing or just submit a document ? i am new to open source and i would really appreciate the help

**Comment by sithumonline** [comment]
> hey! i'd like to contribute to this , but i have a question. do we have to create a react page for the doc we are writing or just submit a document ? i am new to open source and i would really appreciate the help

Hello @KanishkKhurana , You have to write doc in `markdown` ref https://zero2hero.sliitfoss.org/docs/tutorial-basics/create-a-document#create-your-first-doc after that PR it.

**Comment by sithumonline** [comment]
Read more for further information https://docusaurus.io/docs

**Comment by KanishkKhurana** [comment]
this looks good ! please assign this to me and i'll get this done asap!
