### ISSUE TITLE
Write a doc about docker-compose

### ISSUE THREAD

**Issue by sithumonline** [sliit-foss/zero2hero#22]
**_Please assign yourself before you start work on it._**

**Comment by RahulPalve** [comment]
@sithumonline  , Do you need docker-compose file or want info regarding docker-compose?

**Comment by sithumonline** [comment]
> @sithumonline , Do you need docker-compose file or want info regarding docker-compose?

yha, like info with a simple example how write docker-compose file and how to use it. You can provide some screenshots like medium article.

**Comment by RahulPalve** [comment]
@sithumonline ok , will do that
