### ISSUE TITLE
Write a doc about Flutter

### ISSUE THREAD

**Issue by sithumonline** [sliit-foss/zero2hero#24]
**_Please assign yourself before you start work on it._**

**Comment by iMeriem** [comment]
Hey, I'd like to work on this issue. Can you assign it to me ?
Thanks

**Comment by sithumonline** [comment]
Hi @iMeriem any updates?

**Comment by iMeriem** [comment]
Hello @sithumonline Sorry for the late reply. 
I'm finalising my markdown to be ready for commit

**Comment by sithumonline** [comment]
> is this issue open to work ?

Sorry this one is done
