### ISSUE TITLE
Write a doc about Github Actions

### ISSUE THREAD

**Issue by sithumonline** [sliit-foss/zero2hero#25]
**_Please assign yourself before you start work on it._**

**Comment by vismitap** [comment]
Hey, I would like to work on this issue! Please assign this to me.

**Comment by sithumonline** [comment]
> Hey, I would like to work on this issue! Please assign this to me.
> 

Hello @vismitap can I know status of this issue?

**Comment by vismitap** [comment]
> > Hey, I would like to work on this issue! Please assign this to me.
> 
> Hello @vismitap can I know status of this issue?

Working on it, will raise a PR today

**Comment by sithumonline** [comment]
> > > Hey, I would like to work on this issue! Please assign this to me.
> > 
> > 
> > Hello @vismitap can I know status of this issue?
> 
> Working on it, will raise a PR today

Cool, thanks for the quick reply 😇

**Comment by vismitap** [comment]
Hey where do I add the Readme file? I need to make a new folder called Github Actions inside docs ig. So it will be /docs/Github Actions/Github Actions.md right?

**Comment by sithumonline** [comment]
> Hey where do I add the Readme file? I need to make a new folder called Github Actions inside docs ig. So it will be /docs/Github Actions/Github Actions.md right?

yp, it's `/docs/Github Actions/Github Actions.md`

- Add `sidebar_positio` https://github.com/sliit-foss/zero2hero/blob/68c6d026b7dcfd5be18694e8ba7f854fb19e2a39/docs/machine-learning/coco-ssd.md#L2
-  Add `_category_.json` file with **label** and **position** https://github.com/sliit-foss/zero2hero/blob/68c6d026b7dcfd5be18694e8ba7f854fb19e2a39/docs/machine-learning/_category_.json#L2
