### ISSUE TITLE
Write a doc about serverless hosting/Heroku

### ISSUE THREAD

**Issue by sithumonline** [sliit-foss/zero2hero#44]
Write under `serverless-hosting/heroku`
**_Please assign yourself before you start work on it._**

**Comment by Mirza-Hassan** [comment]
@sithumonline please assign me

**Comment by Mirza-Hassan** [comment]
@sithumonline can you please review this PR https://github.com/sliit-foss/zero2hero/pull/104

**Comment by MadhushaPrasad** [comment]
@sithumonline is this issue finished?
